rep = "visualizer"
deploy:
    yarn run build
    cp -rf ./dist ~/ws/.term/dist
    cp ~/ws/.conf/fr/just/dep ~/ws/.term/dist/
    mv ~/ws/.term/dist/dep ~/ws/.term/dist/justfile
    rm -rf ./dist
    (cd ~/ws/.term/dist && just deploy {{rep}})
    rm -rf ~/ws/.term/dist
